name: Reset User Milestones

on:
  schedule:
    - cron: '1 14 * * 6'  # 00:01 AEST Sunday = 14:01 UTC Saturday

jobs:
  run-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run cleanup job
        run: go run jobs/reset_user_milestones.go
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}